export default {
  title: "Vite starter title",
  header: {
    phone: "+7 (927) 249-40-69",
    phoneHref: "tel:+79272494069",
    nav: [
      { label: "О проекте", href: "#about" },
      { label: "Расположение", href: "#location" },
      { label: "Планировки", href: "#layouts" },
      { label: "Акции", href: "#promotions" },
      { label: "Контакты", href: "/contacts.html" },
    ],
    mobileNav: [
      { label: "О проекте", href: "#about" },
      { label: "Особенности проекта", href: "#features" },
      { label: "Ход строительства", href: "#progress" },
      { label: "Квартиры", href: "#layouts" },
      { label: "Инфраструктура", href: "#infrastructure" },
      { label: "Преимущества", href: "#benefits" },
      { label: "Акции", href: "#promotions" },
    ],
    apartments: {
      label: "Выбрать квартиру",
      href: "#layouts",
    },
    callback: {
      label: "Заказать звонок",
      href: "#callback-dialog",
    },
  },
  footer: {
    phone: "+7 (495) 132-07-08",
    phoneHref: "tel:+74951320708",
    nav: [
      { label: "О проекте", href: "#about" },
      { label: "Расположение", href: "#location" },
      { label: "Особенности проекта", href: "#features" },
      { label: "Планировки", href: "#layouts" },
      { label: "Инфраструктура", href: "#infrastructure" },
      { label: "Акции", href: "#promotions" },
      { label: "Преимущества", href: "#benefits" },
      { label: "Как купить", href: "#buy" },
      { label: "Ход строительства", href: "#progress" },
      { label: "контакты", href: "/contacts.html" },
    ],
    mobileNav: [
      { label: "О проекте", href: "#about" },
      { label: "Особенности проекта", href: "#features" },
      { label: "Инфраструктура", href: "#infrastructure" },
      { label: "Преимущества", href: "#benefits" },
      { label: "Расположение", href: "#location" },
      { label: "Квартиры", href: "#layouts" },
      { label: "Акции", href: "#promotions" },
      { label: "Как купить", href: "#buy" },
    ],
    legalLinks: [
      { label: "Проектная декларация", href: "#" },
      { label: "Документы", href: "#" },
      { label: "Политика конфиденциальности", href: "#" },
    ],
    disclaimer:
      "ПРЕДСТАВЛЕННАЯ ИНФОРМАЦИЯ НОСИТ ИСКЛЮЧИТЕЛЬНО ОЗНАКОМИТЕЛЬНЫЙ ХАРАКТЕР, НИ ПРИ КАКИХ ОБСТОЯТЕЛЬСТВАХ НЕ ЯВЛЯЕТСЯ ПУБЛИЧНОЙ ОФЕРТОЙ, ОПРЕДЕЛЯЕМОЙ ПОЛОЖЕНИЯМИ СТАТЬИ 437 ГК РФ. ПОСТРОЕННЫЕ ОБЪЕКТЫ МОГУТ ОТЛИЧАТЬСЯ ОТ ПРЕДСТАВЛЕННЫХ 3D-ВИЗУАЛИЗАЦИЙ, ИЗОБРАЖЕНИЙ. ВСЕ ПРЕДСТАВЛЕННЫЕ МАТЕРИАЛЫ, ИЗОБРАЖЕНИЯ ЯВЛЯЮТСЯ ОРИЕНТИРОВОЧНЫМИ, В НИХ МОГУТ БЫТЬ ВНЕСЕНЫ ЛЮБЫЕ ИЗМЕНЕНИЯ И ДОПОЛНЕНИЯ.",
    studioUrl: "https://markweber.ru/",
    year: "2026",
  },
};
